#!/usr/bin/env python
# -*- coding: utf-8 -*- 

from pydna import pcr, parse

#TDH3p PsXYL1(K270R) ADH1t
#PGK1p PsXYL2 PGK1t  URA3
#{Bettiga et al., 2009}
# Lys270Arg


'''
>5XYL1s 
GCGGATCCTCTAGAATGCCTT
>3XYL1s 
TTGGATCCTCTAGATTAGACGAAG
>5K270R 
CATCATTCCAAGGTCCAACACTG
>3K270R 
CAGTGTTGGACCTTGGAATGATG
>pY7-XR-for 
GCAAGCTTGGCGCGCCGGGATCGAAGAAATGATGG
>pY7-XR-rev 
CGCGCGCGCTGCAGGTGTGGAAGAACGATTACAAC
>pY7-XDH-for 
GCCTGCAGTCTAACTGATCTATCCAAAACTG
>pY7-XDH-rev 
CGTGAGCTCCGTACGTAACGAACGCAGAATTTTC
'''

